// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "iSpy",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "iSpy",
            targets: ["AppModule"],
            bundleIdentifier: "com.emilianoUrnice.iSpy",
            teamIdentifier: "47V6XN83NZ",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .car),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("MLFile/MultiLabelModel.mlmodelc")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
